// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package account

import (
	"github.com/oldme-git/36hour/app/gateway/api/account"
)

type ControllerAdmin struct{}

func NewAdmin() account.IAccountAdmin {
	return &ControllerAdmin{}
}
