// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package account

import (
	"github.com/oldme-git/36hour/app/gateway/api/account"
)

type ControllerV1 struct{}

func NewV1() account.IAccountV1 {
	return &ControllerV1{}
}
