apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name : main
          imagePullPolicy: Always
          volumeMounts:
            - name: conf-volume
              mountPath: /app/config.yaml
              subPath: gateway.yaml

            - name: conf-volume
              mountPath: /app/etcd.yaml
              subPath: etcd.yaml
      volumes:
        - configMap:
            defaultMode: 420
            name: conf
          name: conf-volume
      imagePullSecrets:
        - name: 36hour-aliyun