// protoc --go_out=plugins=grpc:. *.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: policy_prepare/v1/policy_prepare.proto

package v1

import (
	reflect "reflect"
	pbentity "seat/api/pbentity"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePolicyPrepareReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" v:"required"`          // v:required
	Policy string `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty" v:"required|json"` // v:required|json
}

func (x *CreatePolicyPrepareReq) Reset() {
	*x = CreatePolicyPrepareReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_policy_prepare_v1_policy_prepare_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePolicyPrepareReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePolicyPrepareReq) ProtoMessage() {}

func (x *CreatePolicyPrepareReq) ProtoReflect() protoreflect.Message {
	mi := &file_policy_prepare_v1_policy_prepare_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePolicyPrepareReq.ProtoReflect.Descriptor instead.
func (*CreatePolicyPrepareReq) Descriptor() ([]byte, []int) {
	return file_policy_prepare_v1_policy_prepare_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePolicyPrepareReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePolicyPrepareReq) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

type CreatePolicyPrepareRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreatePolicyPrepareRes) Reset() {
	*x = CreatePolicyPrepareRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_policy_prepare_v1_policy_prepare_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePolicyPrepareRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePolicyPrepareRes) ProtoMessage() {}

func (x *CreatePolicyPrepareRes) ProtoReflect() protoreflect.Message {
	mi := &file_policy_prepare_v1_policy_prepare_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePolicyPrepareRes.ProtoReflect.Descriptor instead.
func (*CreatePolicyPrepareRes) Descriptor() ([]byte, []int) {
	return file_policy_prepare_v1_policy_prepare_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePolicyPrepareRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOnePolicyPrepareReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" v:"required"` // v:required
}

func (x *GetOnePolicyPrepareReq) Reset() {
	*x = GetOnePolicyPrepareReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_policy_prepare_v1_policy_prepare_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOnePolicyPrepareReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnePolicyPrepareReq) ProtoMessage() {}

func (x *GetOnePolicyPrepareReq) ProtoReflect() protoreflect.Message {
	mi := &file_policy_prepare_v1_policy_prepare_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnePolicyPrepareReq.ProtoReflect.Descriptor instead.
func (*GetOnePolicyPrepareReq) Descriptor() ([]byte, []int) {
	return file_policy_prepare_v1_policy_prepare_proto_rawDescGZIP(), []int{2}
}

func (x *GetOnePolicyPrepareReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOnePolicyPrepareRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PolicyPrepare *pbentity.PolicyPrepare `protobuf:"bytes,1,opt,name=policy_prepare,json=policyPrepare,proto3" json:"policy_prepare,omitempty"`
}

func (x *GetOnePolicyPrepareRes) Reset() {
	*x = GetOnePolicyPrepareRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_policy_prepare_v1_policy_prepare_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOnePolicyPrepareRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnePolicyPrepareRes) ProtoMessage() {}

func (x *GetOnePolicyPrepareRes) ProtoReflect() protoreflect.Message {
	mi := &file_policy_prepare_v1_policy_prepare_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnePolicyPrepareRes.ProtoReflect.Descriptor instead.
func (*GetOnePolicyPrepareRes) Descriptor() ([]byte, []int) {
	return file_policy_prepare_v1_policy_prepare_proto_rawDescGZIP(), []int{3}
}

func (x *GetOnePolicyPrepareRes) GetPolicyPrepare() *pbentity.PolicyPrepare {
	if x != nil {
		return x.PolicyPrepare
	}
	return nil
}

type GetListPolicyPrepareReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int32  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty" v:"required"`                 // v:required
	PageSize int32  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty" v:"required|max:100"` // v:required|max:100
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty" v:"length:1,20"`               // v:length:1,20
}

func (x *GetListPolicyPrepareReq) Reset() {
	*x = GetListPolicyPrepareReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_policy_prepare_v1_policy_prepare_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListPolicyPrepareReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListPolicyPrepareReq) ProtoMessage() {}

func (x *GetListPolicyPrepareReq) ProtoReflect() protoreflect.Message {
	mi := &file_policy_prepare_v1_policy_prepare_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListPolicyPrepareReq.ProtoReflect.Descriptor instead.
func (*GetListPolicyPrepareReq) Descriptor() ([]byte, []int) {
	return file_policy_prepare_v1_policy_prepare_proto_rawDescGZIP(), []int{4}
}

func (x *GetListPolicyPrepareReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListPolicyPrepareReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetListPolicyPrepareReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetListPolicyPrepareRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PolicyPrepares []*pbentity.PolicyPrepare `protobuf:"bytes,1,rep,name=policy_prepares,json=policyPrepares,proto3" json:"policy_prepares,omitempty"`
}

func (x *GetListPolicyPrepareRes) Reset() {
	*x = GetListPolicyPrepareRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_policy_prepare_v1_policy_prepare_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListPolicyPrepareRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListPolicyPrepareRes) ProtoMessage() {}

func (x *GetListPolicyPrepareRes) ProtoReflect() protoreflect.Message {
	mi := &file_policy_prepare_v1_policy_prepare_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListPolicyPrepareRes.ProtoReflect.Descriptor instead.
func (*GetListPolicyPrepareRes) Descriptor() ([]byte, []int) {
	return file_policy_prepare_v1_policy_prepare_proto_rawDescGZIP(), []int{5}
}

func (x *GetListPolicyPrepareRes) GetPolicyPrepares() []*pbentity.PolicyPrepare {
	if x != nil {
		return x.PolicyPrepares
	}
	return nil
}

type UpdatePolicyPrepareReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" v:"required"`              // v:required
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" v:"required"`          // v:required
	Policy string `protobuf:"bytes,3,opt,name=policy,proto3" json:"policy,omitempty" v:"required|json"` // v:required|json
}

func (x *UpdatePolicyPrepareReq) Reset() {
	*x = UpdatePolicyPrepareReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_policy_prepare_v1_policy_prepare_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePolicyPrepareReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePolicyPrepareReq) ProtoMessage() {}

func (x *UpdatePolicyPrepareReq) ProtoReflect() protoreflect.Message {
	mi := &file_policy_prepare_v1_policy_prepare_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePolicyPrepareReq.ProtoReflect.Descriptor instead.
func (*UpdatePolicyPrepareReq) Descriptor() ([]byte, []int) {
	return file_policy_prepare_v1_policy_prepare_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePolicyPrepareReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePolicyPrepareReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePolicyPrepareReq) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

type UpdatePolicyPrepareRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdatePolicyPrepareRes) Reset() {
	*x = UpdatePolicyPrepareRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_policy_prepare_v1_policy_prepare_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePolicyPrepareRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePolicyPrepareRes) ProtoMessage() {}

func (x *UpdatePolicyPrepareRes) ProtoReflect() protoreflect.Message {
	mi := &file_policy_prepare_v1_policy_prepare_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePolicyPrepareRes.ProtoReflect.Descriptor instead.
func (*UpdatePolicyPrepareRes) Descriptor() ([]byte, []int) {
	return file_policy_prepare_v1_policy_prepare_proto_rawDescGZIP(), []int{7}
}

type DeletePolicyPrepareReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" v:"required"` // v:required
}

func (x *DeletePolicyPrepareReq) Reset() {
	*x = DeletePolicyPrepareReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_policy_prepare_v1_policy_prepare_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePolicyPrepareReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePolicyPrepareReq) ProtoMessage() {}

func (x *DeletePolicyPrepareReq) ProtoReflect() protoreflect.Message {
	mi := &file_policy_prepare_v1_policy_prepare_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePolicyPrepareReq.ProtoReflect.Descriptor instead.
func (*DeletePolicyPrepareReq) Descriptor() ([]byte, []int) {
	return file_policy_prepare_v1_policy_prepare_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePolicyPrepareReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePolicyPrepareRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeletePolicyPrepareRes) Reset() {
	*x = DeletePolicyPrepareRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_policy_prepare_v1_policy_prepare_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePolicyPrepareRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePolicyPrepareRes) ProtoMessage() {}

func (x *DeletePolicyPrepareRes) ProtoReflect() protoreflect.Message {
	mi := &file_policy_prepare_v1_policy_prepare_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePolicyPrepareRes.ProtoReflect.Descriptor instead.
func (*DeletePolicyPrepareRes) Descriptor() ([]byte, []int) {
	return file_policy_prepare_v1_policy_prepare_proto_rawDescGZIP(), []int{9}
}

var File_policy_prepare_v1_policy_prepare_proto protoreflect.FileDescriptor

var file_policy_prepare_v1_policy_prepare_proto_rawDesc = []byte{
	0x0a, 0x26, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x70, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65,
	0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x70, 0x72, 0x65, 0x70, 0x61,
	0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x73, 0x65, 0x61, 0x74, 0x1a, 0x1d,
	0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f,
	0x70, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a,
	0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x50, 0x72, 0x65,
	0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x22, 0x28, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x28, 0x0a,
	0x16, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x50, 0x72, 0x65,
	0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x58, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4f, 0x6e,
	0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65,
	0x73, 0x12, 0x3e, 0x0a, 0x0e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x70, 0x72, 0x65, 0x70,
	0x61, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x50, 0x72, 0x65, 0x70, 0x61,
	0x72, 0x65, 0x52, 0x0d, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72,
	0x65, 0x22, 0x5d, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x5b, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x12, 0x40, 0x0a, 0x0f, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x70, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e,
	0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x0e, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x73, 0x22, 0x54, 0x0a,
	0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x50, 0x72, 0x65,
	0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x22, 0x18, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x22, 0x28, 0x0a,
	0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x50, 0x72, 0x65,
	0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65,
	0x73, 0x32, 0xfa, 0x02, 0x0a, 0x0d, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x50, 0x72, 0x65, 0x70,
	0x61, 0x72, 0x65, 0x12, 0x46, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x2e,
	0x73, 0x65, 0x61, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x73, 0x65,
	0x61, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x50,
	0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x06, 0x47,
	0x65, 0x74, 0x4f, 0x6e, 0x65, 0x12, 0x1c, 0x2e, 0x73, 0x65, 0x61, 0x74, 0x2e, 0x47, 0x65, 0x74,
	0x4f, 0x6e, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x73, 0x65, 0x61, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x6e,
	0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65,
	0x73, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1d,
	0x2e, 0x73, 0x65, 0x61, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e,
	0x73, 0x65, 0x61, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x46,
	0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x73, 0x65, 0x61, 0x74, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x50, 0x72, 0x65, 0x70,
	0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x73, 0x65, 0x61, 0x74, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72,
	0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x12, 0x1c, 0x2e, 0x73, 0x65, 0x61, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1c,
	0x2e, 0x73, 0x65, 0x61, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x11,
	0x5a, 0x0f, 0x73, 0x65, 0x61, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_policy_prepare_v1_policy_prepare_proto_rawDescOnce sync.Once
	file_policy_prepare_v1_policy_prepare_proto_rawDescData = file_policy_prepare_v1_policy_prepare_proto_rawDesc
)

func file_policy_prepare_v1_policy_prepare_proto_rawDescGZIP() []byte {
	file_policy_prepare_v1_policy_prepare_proto_rawDescOnce.Do(func() {
		file_policy_prepare_v1_policy_prepare_proto_rawDescData = protoimpl.X.CompressGZIP(file_policy_prepare_v1_policy_prepare_proto_rawDescData)
	})
	return file_policy_prepare_v1_policy_prepare_proto_rawDescData
}

var file_policy_prepare_v1_policy_prepare_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_policy_prepare_v1_policy_prepare_proto_goTypes = []interface{}{
	(*CreatePolicyPrepareReq)(nil),  // 0: seat.CreatePolicyPrepareReq
	(*CreatePolicyPrepareRes)(nil),  // 1: seat.CreatePolicyPrepareRes
	(*GetOnePolicyPrepareReq)(nil),  // 2: seat.GetOnePolicyPrepareReq
	(*GetOnePolicyPrepareRes)(nil),  // 3: seat.GetOnePolicyPrepareRes
	(*GetListPolicyPrepareReq)(nil), // 4: seat.GetListPolicyPrepareReq
	(*GetListPolicyPrepareRes)(nil), // 5: seat.GetListPolicyPrepareRes
	(*UpdatePolicyPrepareReq)(nil),  // 6: seat.UpdatePolicyPrepareReq
	(*UpdatePolicyPrepareRes)(nil),  // 7: seat.UpdatePolicyPrepareRes
	(*DeletePolicyPrepareReq)(nil),  // 8: seat.DeletePolicyPrepareReq
	(*DeletePolicyPrepareRes)(nil),  // 9: seat.DeletePolicyPrepareRes
	(*pbentity.PolicyPrepare)(nil),  // 10: pbentity.PolicyPrepare
}
var file_policy_prepare_v1_policy_prepare_proto_depIdxs = []int32{
	10, // 0: seat.GetOnePolicyPrepareRes.policy_prepare:type_name -> pbentity.PolicyPrepare
	10, // 1: seat.GetListPolicyPrepareRes.policy_prepares:type_name -> pbentity.PolicyPrepare
	0,  // 2: seat.PolicyPrepare.Create:input_type -> seat.CreatePolicyPrepareReq
	2,  // 3: seat.PolicyPrepare.GetOne:input_type -> seat.GetOnePolicyPrepareReq
	4,  // 4: seat.PolicyPrepare.GetList:input_type -> seat.GetListPolicyPrepareReq
	6,  // 5: seat.PolicyPrepare.Update:input_type -> seat.UpdatePolicyPrepareReq
	8,  // 6: seat.PolicyPrepare.Delete:input_type -> seat.DeletePolicyPrepareReq
	1,  // 7: seat.PolicyPrepare.Create:output_type -> seat.CreatePolicyPrepareRes
	3,  // 8: seat.PolicyPrepare.GetOne:output_type -> seat.GetOnePolicyPrepareRes
	5,  // 9: seat.PolicyPrepare.GetList:output_type -> seat.GetListPolicyPrepareRes
	7,  // 10: seat.PolicyPrepare.Update:output_type -> seat.UpdatePolicyPrepareRes
	9,  // 11: seat.PolicyPrepare.Delete:output_type -> seat.DeletePolicyPrepareRes
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_policy_prepare_v1_policy_prepare_proto_init() }
func file_policy_prepare_v1_policy_prepare_proto_init() {
	if File_policy_prepare_v1_policy_prepare_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_policy_prepare_v1_policy_prepare_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePolicyPrepareReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_policy_prepare_v1_policy_prepare_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePolicyPrepareRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_policy_prepare_v1_policy_prepare_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOnePolicyPrepareReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_policy_prepare_v1_policy_prepare_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOnePolicyPrepareRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_policy_prepare_v1_policy_prepare_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListPolicyPrepareReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_policy_prepare_v1_policy_prepare_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListPolicyPrepareRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_policy_prepare_v1_policy_prepare_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePolicyPrepareReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_policy_prepare_v1_policy_prepare_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePolicyPrepareRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_policy_prepare_v1_policy_prepare_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePolicyPrepareReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_policy_prepare_v1_policy_prepare_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePolicyPrepareRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_policy_prepare_v1_policy_prepare_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_policy_prepare_v1_policy_prepare_proto_goTypes,
		DependencyIndexes: file_policy_prepare_v1_policy_prepare_proto_depIdxs,
		MessageInfos:      file_policy_prepare_v1_policy_prepare_proto_msgTypes,
	}.Build()
	File_policy_prepare_v1_policy_prepare_proto = out.File
	file_policy_prepare_v1_policy_prepare_proto_rawDesc = nil
	file_policy_prepare_v1_policy_prepare_proto_goTypes = nil
	file_policy_prepare_v1_policy_prepare_proto_depIdxs = nil
}
