// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"seat/internal/dao/internal"
)

// internalLayoutDao is internal type for wrapping internal DAO implements.
type internalLayoutDao = *internal.LayoutDao

// layoutDao is the data access object for table layout.
// You can define custom methods on it to extend its functionality as you wish.
type layoutDao struct {
	internalLayoutDao
}

var (
	// Layout is globally public accessible object for table layout operations.
	Layout = layoutDao{
		internal.NewLayoutDao(),
	}
)

// Fill with you ideas below.
