// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"seat/internal/dao/internal"
)

// internalPolicyPrepareDao is internal type for wrapping internal DAO implements.
type internalPolicyPrepareDao = *internal.PolicyPrepareDao

// policyPrepareDao is the data access object for table policy_prepare.
// You can define custom methods on it to extend its functionality as you wish.
type policyPrepareDao struct {
	internalPolicyPrepareDao
}

var (
	// PolicyPrepare is globally public accessible object for table policy_prepare operations.
	PolicyPrepare = policyPrepareDao{
		internal.NewPolicyPrepareDao(),
	}
)

// Fill with you ideas below.

type PolicyPrepareSearchCondition struct {
	Name     string
	Page     int
	PageSize int
}
