// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"seat/internal/dao/internal"
)

// internalPolicyCommonDao is internal type for wrapping internal DAO implements.
type internalPolicyCommonDao = *internal.PolicyCommonDao

// policyCommonDao is the data access object for table policy_common.
// You can define custom methods on it to extend its functionality as you wish.
type policyCommonDao struct {
	internalPolicyCommonDao
}

var (
	// PolicyCommon is globally public accessible object for table policy_common operations.
	PolicyCommon = policyCommonDao{
		internal.NewPolicyCommonDao(),
	}
)

// Fill with you ideas below.

type PolicyCommonSearchCondition struct {
	Name     string
	Page     int
	PageSize int
}
