// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"libManager/internal/dao/internal"
)

// internalHallDao is internal type for wrapping internal DAO implements.
type internalHallDao = *internal.HallDao

// hallDao is the data access object for table hall.
// You can define custom methods on it to extend its functionality as you wish.
type hallDao struct {
	internalHallDao
}

var (
	// Hall is globally public accessible object for table hall operations.
	Hall = hallDao{
		internal.NewHallDao(),
	}
)

// Fill with you ideas below.
