// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/oldme-git/36hour/app/seat/internal/dao/internal"
)

// internalSeatLogDao is internal type for wrapping internal DAO implements.
type internalSeatLogDao = *internal.SeatLogDao

// seatLogDao is the data access object for table seat_log.
// You can define custom methods on it to extend its functionality as you wish.
type seatLogDao struct {
	internalSeatLogDao
}

var (
	// SeatLog is globally public accessible object for table seat_log operations.
	SeatLog = seatLogDao{
		internal.NewSeatLogDao(),
	}
)

// Fill with you ideas below.
