// protoc --go_out=plugins=grpc:. *.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: layout/v1/layout.proto

package v1

import (
	reflect "reflect"
	_ "seat/api/pbentity"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLayoutReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocationId int32  `protobuf:"varint,1,opt,name=LocationId,proto3" json:"LocationId,omitempty" v:"required"` // v:required
	PolicyCId  int32  `protobuf:"varint,2,opt,name=PolicyCId,proto3" json:"PolicyCId,omitempty" v:"required"`   // v:required
	PolicyInfo string `protobuf:"bytes,3,opt,name=PolicyInfo,proto3" json:"PolicyInfo,omitempty" v:"json"`      // v:json
	LayoutName string `protobuf:"bytes,4,opt,name=LayoutName,proto3" json:"LayoutName,omitempty" v:"required"`  // v:required
	Map        string `protobuf:"bytes,5,opt,name=Map,proto3" json:"Map,omitempty" v:"json"`                    // v:json
	Status     int32  `protobuf:"varint,6,opt,name=Status,proto3" json:"Status,omitempty" v:"required"`         // v:required
	Sort       int32  `protobuf:"varint,7,opt,name=Sort,proto3" json:"Sort,omitempty" v:"required"`             // v:required
}

func (x *CreateLayoutReq) Reset() {
	*x = CreateLayoutReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_layout_v1_layout_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLayoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLayoutReq) ProtoMessage() {}

func (x *CreateLayoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_layout_v1_layout_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLayoutReq.ProtoReflect.Descriptor instead.
func (*CreateLayoutReq) Descriptor() ([]byte, []int) {
	return file_layout_v1_layout_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLayoutReq) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *CreateLayoutReq) GetPolicyCId() int32 {
	if x != nil {
		return x.PolicyCId
	}
	return 0
}

func (x *CreateLayoutReq) GetPolicyInfo() string {
	if x != nil {
		return x.PolicyInfo
	}
	return ""
}

func (x *CreateLayoutReq) GetLayoutName() string {
	if x != nil {
		return x.LayoutName
	}
	return ""
}

func (x *CreateLayoutReq) GetMap() string {
	if x != nil {
		return x.Map
	}
	return ""
}

func (x *CreateLayoutReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateLayoutReq) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type CreateLayoutRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LayoutId int32 `protobuf:"varint,1,opt,name=LayoutId,proto3" json:"LayoutId,omitempty" v:"required"` // v:required
}

func (x *CreateLayoutRes) Reset() {
	*x = CreateLayoutRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_layout_v1_layout_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLayoutRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLayoutRes) ProtoMessage() {}

func (x *CreateLayoutRes) ProtoReflect() protoreflect.Message {
	mi := &file_layout_v1_layout_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLayoutRes.ProtoReflect.Descriptor instead.
func (*CreateLayoutRes) Descriptor() ([]byte, []int) {
	return file_layout_v1_layout_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLayoutRes) GetLayoutId() int32 {
	if x != nil {
		return x.LayoutId
	}
	return 0
}

var File_layout_v1_layout_proto protoreflect.FileDescriptor

var file_layout_v1_layout_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x61, 0x79, 0x6f,
	0x75, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x73, 0x65, 0x61, 0x74, 0x1a, 0x15,
	0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xcd, 0x01, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x79,
	0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x43, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x50, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x43, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x4d, 0x61, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x53, 0x6f, 0x72, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x53, 0x6f,
	0x72, 0x74, 0x22, 0x2d, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x79, 0x6f,
	0x75, 0x74, 0x52, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x49,
	0x64, 0x32, 0x42, 0x0a, 0x06, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x38, 0x0a, 0x06, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x73, 0x65, 0x61, 0x74, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x73,
	0x65, 0x61, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74,
	0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x73, 0x65, 0x61, 0x74, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_layout_v1_layout_proto_rawDescOnce sync.Once
	file_layout_v1_layout_proto_rawDescData = file_layout_v1_layout_proto_rawDesc
)

func file_layout_v1_layout_proto_rawDescGZIP() []byte {
	file_layout_v1_layout_proto_rawDescOnce.Do(func() {
		file_layout_v1_layout_proto_rawDescData = protoimpl.X.CompressGZIP(file_layout_v1_layout_proto_rawDescData)
	})
	return file_layout_v1_layout_proto_rawDescData
}

var file_layout_v1_layout_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_layout_v1_layout_proto_goTypes = []interface{}{
	(*CreateLayoutReq)(nil), // 0: seat.CreateLayoutReq
	(*CreateLayoutRes)(nil), // 1: seat.CreateLayoutRes
}
var file_layout_v1_layout_proto_depIdxs = []int32{
	0, // 0: seat.Layout.Create:input_type -> seat.CreateLayoutReq
	1, // 1: seat.Layout.Create:output_type -> seat.CreateLayoutRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_layout_v1_layout_proto_init() }
func file_layout_v1_layout_proto_init() {
	if File_layout_v1_layout_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_layout_v1_layout_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLayoutReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_layout_v1_layout_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLayoutRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_layout_v1_layout_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_layout_v1_layout_proto_goTypes,
		DependencyIndexes: file_layout_v1_layout_proto_depIdxs,
		MessageInfos:      file_layout_v1_layout_proto_msgTypes,
	}.Build()
	File_layout_v1_layout_proto = out.File
	file_layout_v1_layout_proto_rawDesc = nil
	file_layout_v1_layout_proto_goTypes = nil
	file_layout_v1_layout_proto_depIdxs = nil
}
