// protoc --go_out=plugins=grpc:. *.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: layout/v1/layout.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Layout_Create_FullMethodName = "/seat.Layout/Create"
)

// LayoutClient is the client API for Layout service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LayoutClient interface {
	Create(ctx context.Context, in *CreateLayoutReq, opts ...grpc.CallOption) (*CreateLayoutRes, error)
}

type layoutClient struct {
	cc grpc.ClientConnInterface
}

func NewLayoutClient(cc grpc.ClientConnInterface) LayoutClient {
	return &layoutClient{cc}
}

func (c *layoutClient) Create(ctx context.Context, in *CreateLayoutReq, opts ...grpc.CallOption) (*CreateLayoutRes, error) {
	out := new(CreateLayoutRes)
	err := c.cc.Invoke(ctx, Layout_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LayoutServer is the server API for Layout service.
// All implementations must embed UnimplementedLayoutServer
// for forward compatibility
type LayoutServer interface {
	Create(context.Context, *CreateLayoutReq) (*CreateLayoutRes, error)
	mustEmbedUnimplementedLayoutServer()
}

// UnimplementedLayoutServer must be embedded to have forward compatible implementations.
type UnimplementedLayoutServer struct {
}

func (UnimplementedLayoutServer) Create(context.Context, *CreateLayoutReq) (*CreateLayoutRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedLayoutServer) mustEmbedUnimplementedLayoutServer() {}

// UnsafeLayoutServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LayoutServer will
// result in compilation errors.
type UnsafeLayoutServer interface {
	mustEmbedUnimplementedLayoutServer()
}

func RegisterLayoutServer(s grpc.ServiceRegistrar, srv LayoutServer) {
	s.RegisterService(&Layout_ServiceDesc, srv)
}

func _Layout_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLayoutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayoutServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Layout_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayoutServer).Create(ctx, req.(*CreateLayoutReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Layout_ServiceDesc is the grpc.ServiceDesc for Layout service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Layout_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seat.Layout",
	HandlerType: (*LayoutServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Layout_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "layout/v1/layout.proto",
}
