apiVersion: apps/v1
kind: Deployment
metadata:
  name: lib-manager
spec:
  template:
    spec:
      containers:
        - name : main
          image: registry.cn-hangzhou.aliyuncs.com/36hour/lib-manager:latest
          volumeMounts:
            - name: conf-volume
              mountPath: /app/config.yaml
              subPath: lib-manager.yaml