// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package seat

import (
	"github.com/oldme-git/36hour/app/gateway/api/seat"
)

type ControllerV1 struct{}

func NewV1() seat.ISeatV1 {
	return &ControllerV1{}
}
