apiVersion: apps/v1
kind: Deployment
metadata:
  name: seat
  labels:
    app: seat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seat
  template:
    metadata:
      labels:
        app: seat
    spec:
      containers:
        - name : main
          imagePullPolicy: Always
          volumeMounts:
            - name: conf-volume
              mountPath: /app/config.yaml
              subPath: seat.yaml
      volumes:
        - configMap:
            defaultMode: 420
            name: conf
          name: conf-volume
      imagePullSecrets:
        - name: 36hour-aliyun