// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/oldme-git/36hour/app/lib-manager/internal/repository/db/dao/internal"
)

// internalLocationDao is internal type for wrapping internal DAO implements.
type internalLocationDao = *internal.LocationDao

// locationDao is the data access object for table location.
// You can define custom methods on it to extend its functionality as you wish.
type locationDao struct {
	internalLocationDao
}

var (
	// Location is globally public accessible object for table location operations.
	Location = locationDao{
		internal.NewLocationDao(),
	}
)

// Fill with you ideas below.
