apiVersion: apps/v1
kind: Deployment
metadata:
  name: seat
spec:
  template:
    spec:
      containers:
        - name : main
          image: registry.cn-hangzhou.aliyuncs.com/36hour/seat:latest
          volumeMounts:
            - name: conf-volume
              mountPath: /app/config.yaml
              subPath: seat.yaml