// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"user/internal/dao/internal"
)

// internalUserMainDao is internal type for wrapping internal DAO implements.
type internalUserMainDao = *internal.UserMainDao

// userMainDao is the data access object for table user_main.
// You can define custom methods on it to extend its functionality as you wish.
type userMainDao struct {
	internalUserMainDao
}

var (
	// UserMain is globally public accessible object for table user_main operations.
	UserMain = userMainDao{
		internal.NewUserMainDao(),
	}
)

// Fill with you ideas below.
