// protoc --go_out=plugins=grpc:. *.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: policy_common/v1/policy_common.proto

package v1

import (
	reflect "reflect"
	pbentity "seat/api/pbentity"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePolicyCommonReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" v:"required"`      // v:required
	Info string `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty" v:"required|json"` // v:required|json
}

func (x *CreatePolicyCommonReq) Reset() {
	*x = CreatePolicyCommonReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_policy_common_v1_policy_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePolicyCommonReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePolicyCommonReq) ProtoMessage() {}

func (x *CreatePolicyCommonReq) ProtoReflect() protoreflect.Message {
	mi := &file_policy_common_v1_policy_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePolicyCommonReq.ProtoReflect.Descriptor instead.
func (*CreatePolicyCommonReq) Descriptor() ([]byte, []int) {
	return file_policy_common_v1_policy_common_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePolicyCommonReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePolicyCommonReq) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type CreatePolicyCommonRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreatePolicyCommonRes) Reset() {
	*x = CreatePolicyCommonRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_policy_common_v1_policy_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePolicyCommonRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePolicyCommonRes) ProtoMessage() {}

func (x *CreatePolicyCommonRes) ProtoReflect() protoreflect.Message {
	mi := &file_policy_common_v1_policy_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePolicyCommonRes.ProtoReflect.Descriptor instead.
func (*CreatePolicyCommonRes) Descriptor() ([]byte, []int) {
	return file_policy_common_v1_policy_common_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePolicyCommonRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOnePolicyCommonReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" v:"required"` // v:required
}

func (x *GetOnePolicyCommonReq) Reset() {
	*x = GetOnePolicyCommonReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_policy_common_v1_policy_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOnePolicyCommonReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnePolicyCommonReq) ProtoMessage() {}

func (x *GetOnePolicyCommonReq) ProtoReflect() protoreflect.Message {
	mi := &file_policy_common_v1_policy_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnePolicyCommonReq.ProtoReflect.Descriptor instead.
func (*GetOnePolicyCommonReq) Descriptor() ([]byte, []int) {
	return file_policy_common_v1_policy_common_proto_rawDescGZIP(), []int{2}
}

func (x *GetOnePolicyCommonReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOnePolicyCommonRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PolicyCommon *pbentity.PolicyCommon `protobuf:"bytes,1,opt,name=policy_common,json=policyCommon,proto3" json:"policy_common,omitempty"`
}

func (x *GetOnePolicyCommonRes) Reset() {
	*x = GetOnePolicyCommonRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_policy_common_v1_policy_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOnePolicyCommonRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnePolicyCommonRes) ProtoMessage() {}

func (x *GetOnePolicyCommonRes) ProtoReflect() protoreflect.Message {
	mi := &file_policy_common_v1_policy_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnePolicyCommonRes.ProtoReflect.Descriptor instead.
func (*GetOnePolicyCommonRes) Descriptor() ([]byte, []int) {
	return file_policy_common_v1_policy_common_proto_rawDescGZIP(), []int{3}
}

func (x *GetOnePolicyCommonRes) GetPolicyCommon() *pbentity.PolicyCommon {
	if x != nil {
		return x.PolicyCommon
	}
	return nil
}

type GetListPolicyCommonReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int32  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty" v:"required"`         // v:required
	PageSize int32  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty" v:"required"` // v:required
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty" v:"length:1,20"`       // v:length:1,20
}

func (x *GetListPolicyCommonReq) Reset() {
	*x = GetListPolicyCommonReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_policy_common_v1_policy_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListPolicyCommonReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListPolicyCommonReq) ProtoMessage() {}

func (x *GetListPolicyCommonReq) ProtoReflect() protoreflect.Message {
	mi := &file_policy_common_v1_policy_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListPolicyCommonReq.ProtoReflect.Descriptor instead.
func (*GetListPolicyCommonReq) Descriptor() ([]byte, []int) {
	return file_policy_common_v1_policy_common_proto_rawDescGZIP(), []int{4}
}

func (x *GetListPolicyCommonReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListPolicyCommonReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetListPolicyCommonReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetListPolicyCommonRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PolicyCommons []*pbentity.PolicyCommon `protobuf:"bytes,1,rep,name=policy_commons,json=policyCommons,proto3" json:"policy_commons,omitempty"`
}

func (x *GetListPolicyCommonRes) Reset() {
	*x = GetListPolicyCommonRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_policy_common_v1_policy_common_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListPolicyCommonRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListPolicyCommonRes) ProtoMessage() {}

func (x *GetListPolicyCommonRes) ProtoReflect() protoreflect.Message {
	mi := &file_policy_common_v1_policy_common_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListPolicyCommonRes.ProtoReflect.Descriptor instead.
func (*GetListPolicyCommonRes) Descriptor() ([]byte, []int) {
	return file_policy_common_v1_policy_common_proto_rawDescGZIP(), []int{5}
}

func (x *GetListPolicyCommonRes) GetPolicyCommons() []*pbentity.PolicyCommon {
	if x != nil {
		return x.PolicyCommons
	}
	return nil
}

type UpdatePolicyCommonReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" v:"required"`          // v:required
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" v:"required"`      // v:required
	Info string `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty" v:"required|json"` // v:required|json
}

func (x *UpdatePolicyCommonReq) Reset() {
	*x = UpdatePolicyCommonReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_policy_common_v1_policy_common_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePolicyCommonReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePolicyCommonReq) ProtoMessage() {}

func (x *UpdatePolicyCommonReq) ProtoReflect() protoreflect.Message {
	mi := &file_policy_common_v1_policy_common_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePolicyCommonReq.ProtoReflect.Descriptor instead.
func (*UpdatePolicyCommonReq) Descriptor() ([]byte, []int) {
	return file_policy_common_v1_policy_common_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePolicyCommonReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePolicyCommonReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePolicyCommonReq) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type UpdatePolicyCommonRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdatePolicyCommonRes) Reset() {
	*x = UpdatePolicyCommonRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_policy_common_v1_policy_common_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePolicyCommonRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePolicyCommonRes) ProtoMessage() {}

func (x *UpdatePolicyCommonRes) ProtoReflect() protoreflect.Message {
	mi := &file_policy_common_v1_policy_common_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePolicyCommonRes.ProtoReflect.Descriptor instead.
func (*UpdatePolicyCommonRes) Descriptor() ([]byte, []int) {
	return file_policy_common_v1_policy_common_proto_rawDescGZIP(), []int{7}
}

type DeletePolicyCommonReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" v:"required"` // v:required
}

func (x *DeletePolicyCommonReq) Reset() {
	*x = DeletePolicyCommonReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_policy_common_v1_policy_common_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePolicyCommonReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePolicyCommonReq) ProtoMessage() {}

func (x *DeletePolicyCommonReq) ProtoReflect() protoreflect.Message {
	mi := &file_policy_common_v1_policy_common_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePolicyCommonReq.ProtoReflect.Descriptor instead.
func (*DeletePolicyCommonReq) Descriptor() ([]byte, []int) {
	return file_policy_common_v1_policy_common_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePolicyCommonReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePolicyCommonRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeletePolicyCommonRes) Reset() {
	*x = DeletePolicyCommonRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_policy_common_v1_policy_common_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePolicyCommonRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePolicyCommonRes) ProtoMessage() {}

func (x *DeletePolicyCommonRes) ProtoReflect() protoreflect.Message {
	mi := &file_policy_common_v1_policy_common_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePolicyCommonRes.ProtoReflect.Descriptor instead.
func (*DeletePolicyCommonRes) Descriptor() ([]byte, []int) {
	return file_policy_common_v1_policy_common_proto_rawDescGZIP(), []int{9}
}

var File_policy_common_v1_policy_common_proto protoreflect.FileDescriptor

var file_policy_common_v1_policy_common_proto_rawDesc = []byte{
	0x0a, 0x24, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x76, 0x31, 0x2f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x73, 0x65, 0x61, 0x74, 0x1a, 0x1c, 0x70, 0x62,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f, 0x0a, 0x15, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x27, 0x0a, 0x15, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x27, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x54, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x3b, 0x0a, 0x0d, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x0c, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x22, 0x5c, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x57, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x3d, 0x0a, 0x0e, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x0d, 0x70, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x22, 0x4f, 0x0a, 0x15, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x17, 0x0a, 0x15, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x22, 0x27, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x17, 0x0a,
	0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x32, 0xef, 0x02, 0x0a, 0x0c, 0x50, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x44, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x12, 0x1b, 0x2e, 0x73, 0x65, 0x61, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x1b,
	0x2e, 0x73, 0x65, 0x61, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x44, 0x0a,
	0x06, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x12, 0x1b, 0x2e, 0x73, 0x65, 0x61, 0x74, 0x2e, 0x47,
	0x65, 0x74, 0x4f, 0x6e, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x73, 0x65, 0x61, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4f,
	0x6e, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c,
	0x2e, 0x73, 0x65, 0x61, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x73,
	0x65, 0x61, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x06,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x73, 0x65, 0x61, 0x74, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x73, 0x65, 0x61, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x22, 0x00, 0x12, 0x44, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x73,
	0x65, 0x61, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x73, 0x65, 0x61, 0x74,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x73, 0x65, 0x61, 0x74,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_policy_common_v1_policy_common_proto_rawDescOnce sync.Once
	file_policy_common_v1_policy_common_proto_rawDescData = file_policy_common_v1_policy_common_proto_rawDesc
)

func file_policy_common_v1_policy_common_proto_rawDescGZIP() []byte {
	file_policy_common_v1_policy_common_proto_rawDescOnce.Do(func() {
		file_policy_common_v1_policy_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_policy_common_v1_policy_common_proto_rawDescData)
	})
	return file_policy_common_v1_policy_common_proto_rawDescData
}

var file_policy_common_v1_policy_common_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_policy_common_v1_policy_common_proto_goTypes = []interface{}{
	(*CreatePolicyCommonReq)(nil),  // 0: seat.CreatePolicyCommonReq
	(*CreatePolicyCommonRes)(nil),  // 1: seat.CreatePolicyCommonRes
	(*GetOnePolicyCommonReq)(nil),  // 2: seat.GetOnePolicyCommonReq
	(*GetOnePolicyCommonRes)(nil),  // 3: seat.GetOnePolicyCommonRes
	(*GetListPolicyCommonReq)(nil), // 4: seat.GetListPolicyCommonReq
	(*GetListPolicyCommonRes)(nil), // 5: seat.GetListPolicyCommonRes
	(*UpdatePolicyCommonReq)(nil),  // 6: seat.UpdatePolicyCommonReq
	(*UpdatePolicyCommonRes)(nil),  // 7: seat.UpdatePolicyCommonRes
	(*DeletePolicyCommonReq)(nil),  // 8: seat.DeletePolicyCommonReq
	(*DeletePolicyCommonRes)(nil),  // 9: seat.DeletePolicyCommonRes
	(*pbentity.PolicyCommon)(nil),  // 10: pbentity.PolicyCommon
}
var file_policy_common_v1_policy_common_proto_depIdxs = []int32{
	10, // 0: seat.GetOnePolicyCommonRes.policy_common:type_name -> pbentity.PolicyCommon
	10, // 1: seat.GetListPolicyCommonRes.policy_commons:type_name -> pbentity.PolicyCommon
	0,  // 2: seat.PolicyCommon.Create:input_type -> seat.CreatePolicyCommonReq
	2,  // 3: seat.PolicyCommon.GetOne:input_type -> seat.GetOnePolicyCommonReq
	4,  // 4: seat.PolicyCommon.GetList:input_type -> seat.GetListPolicyCommonReq
	6,  // 5: seat.PolicyCommon.Update:input_type -> seat.UpdatePolicyCommonReq
	8,  // 6: seat.PolicyCommon.Delete:input_type -> seat.DeletePolicyCommonReq
	1,  // 7: seat.PolicyCommon.Create:output_type -> seat.CreatePolicyCommonRes
	3,  // 8: seat.PolicyCommon.GetOne:output_type -> seat.GetOnePolicyCommonRes
	5,  // 9: seat.PolicyCommon.GetList:output_type -> seat.GetListPolicyCommonRes
	7,  // 10: seat.PolicyCommon.Update:output_type -> seat.UpdatePolicyCommonRes
	9,  // 11: seat.PolicyCommon.Delete:output_type -> seat.DeletePolicyCommonRes
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_policy_common_v1_policy_common_proto_init() }
func file_policy_common_v1_policy_common_proto_init() {
	if File_policy_common_v1_policy_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_policy_common_v1_policy_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePolicyCommonReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_policy_common_v1_policy_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePolicyCommonRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_policy_common_v1_policy_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOnePolicyCommonReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_policy_common_v1_policy_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOnePolicyCommonRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_policy_common_v1_policy_common_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListPolicyCommonReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_policy_common_v1_policy_common_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListPolicyCommonRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_policy_common_v1_policy_common_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePolicyCommonReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_policy_common_v1_policy_common_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePolicyCommonRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_policy_common_v1_policy_common_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePolicyCommonReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_policy_common_v1_policy_common_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePolicyCommonRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_policy_common_v1_policy_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_policy_common_v1_policy_common_proto_goTypes,
		DependencyIndexes: file_policy_common_v1_policy_common_proto_depIdxs,
		MessageInfos:      file_policy_common_v1_policy_common_proto_msgTypes,
	}.Build()
	File_policy_common_v1_policy_common_proto = out.File
	file_policy_common_v1_policy_common_proto_rawDesc = nil
	file_policy_common_v1_policy_common_proto_goTypes = nil
	file_policy_common_v1_policy_common_proto_depIdxs = nil
}
