// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/oldme-git/36hour/app/user/internal/dao/internal"
)

// internalUserLibDao is internal type for wrapping internal DAO implements.
type internalUserLibDao = *internal.UserLibDao

// userLibDao is the data access object for table user_lib.
// You can define custom methods on it to extend its functionality as you wish.
type userLibDao struct {
	internalUserLibDao
}

var (
	// UserLib is globally public accessible object for table user_lib operations.
	UserLib = userLibDao{
		internal.NewUserLibDao(),
	}
)

// Fill with you ideas below.
