name: Docker Image USER CI

on:
  push:
    branches:
      - master

    paths:
      - "app/user/**"
      - "utility/**"

env:
  TZ: "Asia/Shanghai"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.2"
        run: go version

      - name: Install Dependencies
        run: go mod download

      - name: Build
        run: |
          cd app/user
          GOOS=linux GOARCH=amd64 go build -o user
